### PR TITLE
cards height fix

### LINKED ISSUE #48: varying card heights.
**Describe the bug**
All cards have different heights.

**Expected behavior**
All cards should be of same height.

**Screenshots**
Screenshot from 2020-10-04 10-11-35

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

### PR DESCRIPTION
**Pull request by Atimabh**
# Description

Added a min-height property to the cards to that their height becomes equal for all the cards. also added a min-height property for the event title so that the alignment of the elements inside the card remains the same for every card

Fixes #48 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot
Capture

### CODE REVIEW

**Comment by naman360** [comment]
Why are some properties re-written? I mean you edited them and wrote again. Why so?

**Comment by Atimabh** [comment]
@naman360 That's probably because the original code was written on a different operating system than mine so the line endings are different, Git automatically handles this issue while committing so that;s why you're seeing those extra changes. You can google about Git CRLF and Git LF to know more about this. Moreover the entire code is still the same apart from the changes I made to fix the card height issue, you can check the deploy preview in the Netlify checks too. Hope this helps :)

**Comment by naman360** [comment]
@Atimabh please resolve merge conflicts.

**Comment by Atimabh** [comment]
@naman360 Done

**Review by Dheeraj-01 — APPROVED** [review]

**Pull request merged**
