### PR TITLE
Added Contact Us in Light Dark UI, Added Social Media Icons In Footer, Fixed the particle.js issue with body tag and Added 11 events in events.json

### PR DESCRIPTION
**Pull request by K-jais**
1)Added the contact us section in the website in both light and dark UI.
2)Added Social media icons in the footer of the website and added the appropriate style to it in both light and dark UI.
3)Fixed the particle.js issue with the body tag in which the background-color property of the body tag is interfering with particle.js animations by which the dark mode was not working well.
4)Added 11 events in events.json,
    1)Digital Ocean Hacktoberfest
    2)Google Season of Docs (GSoD)
    3)Season of KDE
    4)Open Mainframe Project Mentorship Program
    5)Linux Kernel Mentorship Program
    6)Redox OS Summer of Code
    7)Mozilla Winter of Security
    8)Hyperledger Mentorship Program
    9)Open Summer of Code
    10)Alibaba Summer of Code
    11)ERPNext Summer of Code

     In light mode,

     Screenshot (2169)

=================================================================================

Screenshot (2170)

=================================================================================

Screenshot (2172)

=================================================================================

In Dark Mode,

Screenshot (2173)

=================================================================================

Screenshot (2174)

=================================================================================

Screenshot (2175)

### CODE REVIEW

**Comment by K-jais** [comment]
Please sir/madam review this pull request first before merging any other pull requests as sir last time there was some problem because of that only. As my repository was not up to date with the project's repository causing some conflicts in my pull request.

**Comment by ruchikamuddinagiri** [comment]
Hi,
The search bar is not clickable. Please fix this.
image

**Comment by K-jais** [comment]
> Hi,
> The search bar is not clickable. Please fix this.

Now I have fixed this issue. Please @ruchikamuddinagiri, @PragatiVerma18 , @naman360 , @servermonk   review this PR once more.

**Comment by K-jais** [comment]
Here see the screenshots.

Screenshot (2176)

==============================================================================

Screenshot (2177)

**Comment by PragatiVerma18** [comment]
Hey @K-jais, the UI looks great, just a few changes would be needed, please squash all the commits such that we have to merge minimum commits, and also please resolve the merge conflicts. Reach out to me or any of the mentors in case of any doubts.

**Comment by K-jais** [comment]
> Hey @K-jais, the UI looks great, just a few changes would be needed, please squash all the commits such that we have to merge minimum commits, and also please resolve the merge conflicts. Reach out to me or any of the mentors in case of any doubts. 

So for that I have to close this PR and make a new one ?

**Comment by K-jais** [comment]
> > Hey @K-jais, the UI looks great, just a few changes would be needed, please squash all the commits such that we have to merge minimum commits, and also please resolve the merge conflicts. Reach out to me or any of the mentors in case of any doubts.
> 
> So for that I have to close this PR and make a new one?

**Comment by K-jais** [comment]
And If I make the new PR it will still take into account the previous commits which I have done for the previous PR. So what should I do now?

**Pull request closed without merging**
