### PR TITLE
Added "About us" section and modified the navbar.

### PR DESCRIPTION
**Pull request by DhairyaDutt**
# Description

Added an "About us" section, which describes the website in more detailed manner. Also I've modified the navbar(which are clickable). I've done it in such a way that it also work properly in the dark mode. Cheers.

## Screenshot
foss

### CODE REVIEW

**Comment by DhairyaDutt** [comment]
I've removed the github logo from the navbar  because it's already present in the "contact us" section.

**Comment by AkshaySharma008** [comment]
Can you attach the screenshot showing the responsiveness of the navbar?

**Comment by DhairyaDutt** [comment]
sure!
foss1

**Comment by AkshaySharma008** [comment]
Merging and closing this thread.

**Pull request merged**
