### PR TITLE
More Info Button Color Change and Ripple Effect

### LINKED ISSUE #213: Adding Position Aware effect to More Info
**Is your feature request related to a problem? Please describe.**
The current button just bounces and doesn't meet the user experience.

**Describe the solution you'd like**
I can add CSS and js codes to make it more interactive

**Describe alternatives you've considered**
Else there are alot of button animation so i could chose anyone from it.

### PR DESCRIPTION
**Pull request by Alenjojo**
# Description

I added the More info button hover color change and ripple effect when the user clicks on it.

Fixes #213  (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by priyakumari02** [comment]
I am GSSOC participant .I want to fix this bug

**Comment by Alenjojo** [comment]
> 
> 
> I am GSSOC participant .I want to fix this bug

This is the PR for the issue that has been solved

**Comment by rudrakshi99** [comment]
@Alenjojo Please add the screenshots and resolve merge conflicts.

**Comment by Alenjojo** [comment]
I'll make an another updated PR

**Pull request closed without merging**
