### PR TITLE
Made Navbar Sticky

### LINKED ISSUE #177: Sticky/Fixed Navbar
**Is your feature request related to a problem? Please describe.**
- Currently, the navbar isn't fixed/sticky on scrolling down.

**Describe the solution you'd like**
- As a participant of GSSoC'21, I would like to make navbar fixed/sticky.

**Describe alternatives you've considered**
- `NA`

### PR DESCRIPTION
**Pull request by Saatvik21**
# Description

I made the navbar sticky/fixed while scrolling down the page.

Fixes #177 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

## Screenshot

https://user-images.githubusercontent.com/61618767/111783568-58468300-88e0-11eb-9abd-d70bb5c95187.mp4

### CODE REVIEW

**Review by rudrakshi99 — APPROVED** [review]

**Comment by rudrakshi99** [comment]
Looks good to me.:+1:

**Comment by Saatvik21** [comment]
> Looks good to me.👍

@rudrakshi99 can you please add labels to this PR

**Comment by rudrakshi99** [comment]
> > Looks good to me.+1
> 
> @rudrakshi99 can you please add labels to this PR

The issue is already labeled, so there is no need to add labels to the PR. Don't worry, you will get the points.

**Comment by Saatvik21** [comment]
> > > Looks good to me.+1
> > 
> > 
> > @rudrakshi99 can you please add labels to this PR
> 
> The issue is already labeled, so there is no need to add labels to the PR. Don't worry, you will get the points.

@rudrakshi99 Hey, I checked my score lately and it isn't increased because there needs to be labels on PR as well, So can you please add them , Thank you!

**Pull request merged**
