### PR TITLE
Added_feature_of_Background_UI_animation_with_particle_JS#158

### LINKED ISSUE #158: Background UI animation with particle JS
**This feature will change the complete look of the website**
Background animation using particle js framework 

**Describe the solution you'd like**
I will add js flies like particle js , app.js and jquery and transform some needed lines in css file  

**GSSOC'21**
I am a GSSOC'21 participant please assign this to me.

**Screenshot**
image
Particle js background

### PR DESCRIPTION
**Pull request by Alik-Kumar-Ghosh**
# Description

Added Feature of background animation using particle js framework.

Fixes #158 

## Type of change

Added files :
  particle js , 
  app.js
   jquery.min.js 
 
Manipulated files:
     index.html
     style.css

## Screenshot
image
image

### CODE REVIEW

**Comment by PragatiVerma18** [comment]
Looks good to me @Alik-Kumar-Ghosh! Just resolve the merge conflicts in `Frontend/style.css` and add a screenshot of the page when there's an event card existing on it, to give a better idea of the UI with this particle js animation. Good work overall, kudos!

**Review by Alik-Kumar-Ghosh — COMMENTED** [review]
Please check conflict has been resolved .
image

**Review by Alik-Kumar-Ghosh — COMMENTED** [review]
image

**Comment by Alik-Kumar-Ghosh** [comment]
@PragatiVerma18 Please check all conflict has been resolved.

***ScreenShot***

image

**Pull request merged**
