### PR TITLE
Issue 268

### LINKED ISSUE #268: Adding feedback form
There should be a feedback form which is going to tell us how our website is helpful for the users , where  we are lacking . i want to work on this issue asgssoc21 participant

### PR DESCRIPTION
**Pull request by kumarishalini6**
fixes #268 
I have made a feedback form so that the users can mark our works.

Document1

### CODE REVIEW

**Comment by kumarishalini6** [comment]
please review my PR

**Comment by AkshaySharma008** [comment]
@kumarishalini6  please update your code with upstream. It has conflicts right now.

**Comment by kumarishalini6** [comment]
i have send the PR again but  still there is conflicts files can you guide me how can i remove it

**Comment by kumarishalini6** [comment]
Please add level

**Comment by AkshaySharma008** [comment]
@kumarishalini6  You have missed or removed some part of the code, due to which the event search is not working, please check everything once again and create a new pul request, I am closing this thread for now.

**Comment by kumarishalini6** [comment]
ok

**Pull request closed without merging**
