### PR TITLE
Added 3 Social Links

### LINKED ISSUE #359: Adding social links
I want to add:
website link: https://dsc.community.dev/jss-academy-of-technical-education-noida/
discord link: https://discord.com/invite/EBgD52V2hM
telegram link: https://t.me/DSCJSSATEN

Please assign me this issue under the ggsoc'21 tag

### PR DESCRIPTION
**Pull request by Yunika-Bajracharya**
# Description

I have added the following social links:
Website: https://www.dscjss.in/
Medium: https://medium.com/dsc-jss-noida
YouTube: https://www.youtube.com/channel/UCkELk5JFDceaSf8pBa19kDQ

Fixes #359 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshot
image

### CODE REVIEW

**Comment by Yunika-Bajracharya** [comment]
@AkshaySharma008 Please review my pr.

**Comment by AkshaySharma008** [comment]
Is there any Issue associated with this?

**Comment by AkshaySharma008** [comment]
Because I think this is not required, all the other links are there at the bottom section. If there is no issue assigned over this thing then I won't be moving ahead with this PR.

**Comment by Yunika-Bajracharya** [comment]
> Because I think this is not required, all the other links are there at the bottom section. If there is no issue assigned over this thing then I won't be moving ahead with this PR.

@AkshaySharma008 This is associated with issue #359, which was assigned to me. 
I thought of adding the links to the website, medium, and YouTube along with the existing links because these weren't present on the site.

**Pull request merged**
