### PR TITLE
Created about page for FOSS events website

### PR DESCRIPTION
**Pull request by fatma-sia27**
https://user-images.githubusercontent.com/77666526/113425141-fe20e400-93ee-11eb-98d4-6664f67abe84.mp4
WhatsApp Image 2021-04-02 at 8 00 31 PM (1)

Hey @rudrakshi99 @PragatiVerma18 , issue #175 was assigned to me . So, I had created About page . Please review it and let me know if any changes required. I had created a folder named related_images in which all the images are there which are used in html file.
Thank you.

### CODE REVIEW

**Comment by AkshaySharma008** [comment]
What changes you have made in the Backend Branch? 
You have merge conflicts please rectify them, and I don't think you will need anything from the Backend Branch unless you are not working with Dynamic Application, which we are not doing right now I guess.

**Comment by AkshaySharma008** [comment]
@fatma-sia27, please have a look and then resolve all the conflicts and then revert back with your reason for working in the backend branch.

**Comment by fatma-sia27** [comment]
> @fatma-sia27, please have a look and then resolve all the conflicts and then revert back with your reason for working in the backend branch.

Hey @AkshaySharma008 , actually I am new to open source , so when I was making my pull request then they asked me to change the branch, and there only two branches were showing. So I choose backend. I am attaching image of that .
Since I am beginner so please guide me. Please tell me in which branch should I make my PR . I had made frontend of "About us" page as shown above. 
Please help me.
Thank you.
github_fossEvent

**Comment by fatma-sia27** [comment]
> @fatma-sia27, please have a look and then resolve all the conflicts and then revert back with your reason for working in the backend branch.

foss
@AkshaySharma008 Here I had choosen frontend but that 'compare and pul request' button has not been activated. Please suggest me what should I do next.

**Pull request closed without merging**
