### PR TITLE
Enhanced the toggle style on issue #227

### PR DESCRIPTION
**Pull request by Inventor77**
# Description

Enhanced the Style of toggle button and Added simple and subtle Animations to toggle Button Only Ussing Css makes Site code much lighter due to Deletion of unwanted Lines if HTML and CSS code.
and 

Fixes # 227

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshot
Four ScreenShots Added Comparing between older and New UI

Screenshot (558)
Screenshot (561)
Screenshot (562)
Screenshot (563)

### CODE REVIEW

**Comment by AkshaySharma008** [comment]
@Inventor77 great job, but can you please fetch the latest code and then update your PR. I can see merge conflicts here. 

Looking forward.

**Comment by Inventor77** [comment]
> @Inventor77 great job, but can you please fetch the latest code and then update your PR. I can see merge conflicts here. 
> 
> Looking forward.

Yes Sir By the Evening I will Definitely Do it

**Comment by Inventor77** [comment]
I tried Resolving the conflicts Please do Checkout

**Comment by Inventor77** [comment]
@AkshaySharma008

**Comment by AkshaySharma008** [comment]
Merged. Congratulation and keep contributing @Inventor77.

**Comment by AkshaySharma008** [comment]
@Inventor77 please check, there is something wrong with your code, after merging it just broke the whole CSS file, and I have to revert it back. Please check carefully.

**Comment by Inventor77** [comment]
> @Inventor77 please check, there is something wrong with your code, after merging it just broke the whole CSS file, and I have to revert it back. Please check carefully.

Sir Please can you tell me what is Wrong with it

**Comment by AkshaySharma008** [comment]
You have changes in package.json and CSS files that might be creating some issues. I would suggest don't remove another piece of code unless you are 100% sure of what you are removing. 

I would say pull the repo again and then do change as per your issue and then just push, do not remove any other piece of code.

**Comment by Inventor77** [comment]
@AkshaySharma008 Sir I did as you said please do check it Again

**Comment by AkshaySharma008** [comment]
I can't see any new commits @Inventor77 , please check

**Comment by AkshaySharma008** [comment]
Create a New PR , that would be better

**Comment by Inventor77** [comment]
> 
> 
> Create a New PR , that would be better

Yes Sir

**Comment by Inventor77** [comment]
Sir I have Solved all conflicts now Even togglebranch is 21 commits ahead of master please do Check it and I think there is no need to create new PR


Screenshot (579)

**Comment by Inventor77** [comment]
@AkshaySharma008 Sir please do checkout Now and I apologies for my Mistakes and for wasting your Time

**Comment by AkshaySharma008** [comment]
I can see only 2 branches in the main repo. Please check

**Comment by AkshaySharma008** [comment]
I am asking for new PR because this thread is already closed so, I can't see much to merge your piece of code. 
I would say, 
1. Clone the latest repo or Pull the repo from the origin
2. Do changes in master branch 
3. Push and create a new PR.

**Pull request merged**
