### PR TITLE
ADDED Dark Mode

### PR DESCRIPTION
**Pull request by mohammedjameel24**
# Description
Added Dark Mode

## Type of change
file changes:
index.html
style.css
getEvent.js

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot
opensource

### CODE REVIEW

**Comment by mohammedjameel24** [comment]
> This light-dark mode doesn't save the user's preference of light or dark mode. It will show light mode first every time you open this website. It should save the preference of the user in local storage.

Save it on cookies?

**Comment by K-jais** [comment]
Yeah, you can use cookies but using local storage will be more efficient for this light-dark mode. As in this, we have to store only one value either light or dark.

**Comment by mohammedjameel24** [comment]
done commiting recent changes 

now it saves state of dark mode

#122

**Comment by mohammedjameel24** [comment]
Am not able to resolve merge conflicts . Please guide me
@K-jais

**Comment by K-jais** [comment]
> Am not able to resolve merge conflicts. Please guide me
> @K-jais 

I am not sure but just do one change in style.css as in there from line 115 the whole file gets repeated. But before that just check Now what's the state of the repository in which you are merging is similar to yours or is there something that is not in your repository but in the repository in which you are merging.

**Comment by mohammedjameel24** [comment]
> > Am not able to resolve merge conflicts. Please guide me
> > @K-jais 
> 
> I am not sure but just do one change in style.css as in there from line 115 the whole file gets repeated. But before that just check Now what's the state of the repository in which you are merging is similar to yours or is there something that is not in your repository but in the repository in which you are merging.

Ok trying git pull

**Comment by K-jais** [comment]
Yaa just close your existing request and then make a new pull request.

**Comment by mohammedjameel24** [comment]
All checks have passed , please guide me further @K-jais

**Comment by K-jais** [comment]
> All checks have passed, please guide me further @K-jais

If all the checks have been passed then wait for the reviewers to merge this pull request.

**Comment by mohammedjameel24** [comment]
please review my commits

**Comment by K-jais** [comment]
> please review my commits @K-jais 

I can't I am a participant and not a reviewer or a mentor of this project.

**Comment by mohammedjameel24** [comment]
Please review and merge my pull request

**Comment by ruchikamuddinagiri** [comment]
Please resolve the merge conflicts.

**Comment by mohammedjameel24** [comment]
> Please resolve the merge conflicts.

Can i know what are the conflicts am not sure about them

**Comment by ruchikamuddinagiri** [comment]
> > Please resolve the merge conflicts.
> 
> Can i know what are the conflicts am not sure about them

try pulling from upstream once and comparing changes in your local repository.

**Comment by mohammedjameel24** [comment]
> > > Please resolve the merge conflicts.
> > 
> > Can i know what are the conflicts am not sure about them
> 
> try pulling from upstream once and comparing changes in your local repository.

Ok pulled from upstream and the local server ran well found that dark mode has been already implemented 

? Duplicate PR!!!

**Comment by mohammedjameel24** [comment]
Due to faulty implementation of darkmode in current code base of yours 
There are conflicts 

Please revert back so that i can implement my code for darkmode 
@ruchikamuddinagiri

**Comment by mohammedjameel24** [comment]
> Due to faulty implementation of darkmode in current code base of yours 
> There are conflicts 
> 
> Please revert back so that i can implement my code for darkmode 
> @ruchikamuddinagiri 

Hello?

**Comment by oneknucklehead** [comment]
Hey! the dark mode that was merged does not work properly.
can I get assigned to this issue so that I can work on it under GSSoC'21?

**Comment by mohammedjameel24** [comment]
review my commits and deploy preview

**Pull request closed without merging**
