### PR TITLE
Progressbar Successfully added Issue#269

### PR DESCRIPTION
**Pull request by Inventor77**
# Description

Scroll Progress Bar with Number Percentage On left side of Page is Successfully added

Fixes # (269)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ y ] My code follows the style guidelines of this project
- [ y ] I have performed a self-review of my own code
- [ y ] I have commented my code, particularly in hard-to-understand areas
- [ y ] My changes generate no new warnings
- [ y ] I have added tests that prove my fix is effective or that my feature works

## Screenshot

PercentProgressBar-DarkTheme

PercentProgressBar-LightTheme

### CODE REVIEW

**Comment by Inventor77** [comment]
@PragatiVerma18 Please mam Merge this Pull Request and also Label it's Level too

**Comment by rudrakshi99** [comment]
Link your PR properly with the issue.

**Comment by Inventor77** [comment]
> 
> Link your PR properly with the issue.
>

@rudrakshi99 Mam I don't know how to do it from my side, I googled it but didn't get that but my Issue is #269

**Comment by AkshaySharma008** [comment]
@PragatiVerma18 @Inventor77, I guess there are 2 sidebars coming up , if we are using the left one then remove the right one.

**Comment by Inventor77** [comment]
@rudrakshi99 Mam please tell me is their need to change anything

**Comment by Inventor77** [comment]
@PragatiVerma18  @naman360  @servermonk

Please Mentors give this one Level label and merge it or tell me if any change are needed

**Pull request closed without merging**
