### PR TITLE
Added various security features

### LINKED ISSUE #236: Added various security features issue
**Is your feature request related to a problem? Please describe.**
Improves the security of the website.

**Describe the solution you'd like**
Setting various HTTP headers using helmet
Rate limiter so the server won't get overload.
Added mongo sanitize for data sanitization against noSQL query injection
Added xss for data sanitization against XSS.

I have done this before on another gssoc project with level 2 tag  so, i know this well.
If you find it relevant, please assign me.
I am a GSSOC'21 participant .

### PR DESCRIPTION
**Pull request by krishna-y2000**
# Description

Added helmet for security http headers.
Added rate limiter to receive 100 requests per hour from a particular IP address.
Added mongo sanitize for data sanitization against noSQL query injection
Added xss for data sanitization against XSS.

Please review and if any changes required let me know.
Thank you.

Fixes #236

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshot
Please add screenshot of UI related changes if any, for further reference.

### CODE REVIEW

**Comment by AkshaySharma008** [comment]
Good Job @krishna-y2000, may I know have you test the apis after successful completion of the above points?

**Comment by krishna-y2000** [comment]
@AkshaySharma008  I tested it and found that rate Limiter is responsible for throwing error for ```/event``` url path. I searched and found that this will not work for live-server package .So, will it fine if i remove rate-limiter feature and make a new commit ? Else you can suggest something.

**Comment by AkshaySharma008** [comment]
> @AkshaySharma008 I tested it and found that rate Limiter is responsible for throwing error for `/event` url path. I searched and found that this will not work for live-server package .So, will it fine if i remove rate-limiter feature and make a new commit ? Else you can suggest something.

Rate limit is not implemented correctly, try to implement it correctly.

**Comment by krishna-y2000** [comment]
> > @AkshaySharma008 I tested it and found that rate Limiter is responsible for throwing error for `/event` url path. I searched and found that this will not work for live-server package .So, will it fine if i remove rate-limiter feature and make a new commit ? Else you can suggest something.
> 
> Rate limit is not implemented correctly, try to implement it correctly.

@AkshaySharma008  Yes , I know that. The catch is that  the rate limiter will only work for home pages with express but here the home page is made by live-server npm package. 

I even added the middleware to index.js but it will not work due to above reason.

**Pull request closed without merging**
