### PR TITLE
Added Contact Us section and Social media Icons, Fixed Dark mode UI, Added Events in events.json

### PR DESCRIPTION
**Pull request by K-jais**
# Description

Added the Contact us section and social media icons at the bottom of the page.

Fixed the Dark mode UI.

Added two events,
1)Alibaba Summer of Code
2)ERPNEXT Summer of Code

In Light mode,
Screenshot (2192)
===
Screenshot (2193)
===
Screenshot (2194)

In Dark mode,
Screenshot (2195)
===
Screenshot (2196)
===
Screenshot (2197)

### CODE REVIEW

**Comment by K-jais** [comment]
Its working video is ,

https://user-images.githubusercontent.com/75881393/112527564-33af4700-8dc9-11eb-8b7d-d56b8a511711.mp4

**Comment by K-jais** [comment]
It solves the issue #161 .

Please review this PR first before merging any other PRs. As I have been trying to merge this PR from past 3 days but everytime some other PR is merged its raises some conflicts.

**Comment by K-jais** [comment]
So please @ruchikamuddinagiri @PragatiVerma18  review this PR.

**Comment by ruchikamuddinagiri** [comment]
Good work. Merging your PR.

**Pull request merged**
