### PR TITLE
 changes in appearence of title

### LINKED ISSUE #215: Make modifications in title of event
The title of event described in event cards looks boring.We can change its appearence  to make it look  more attractive which is responsive to event card .

### PR DESCRIPTION
**Pull request by Muskan-creator**
# Description
changes the appearance of title and make it responsive to event card

Fixes #215  (issue)

## Type of change

  please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)-

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot
Please add screenshot of UI related changes if any, for further reference.
screenshot ui

### CODE REVIEW

**Comment by Muskan-creator** [comment]
@PragatiVerma18 Please review my PR and merge it.

**Comment by Muskan-creator** [comment]
@naman360 @PragatiVerma18 Looking forward to make any changes if wanted or needed and if not requesting you to merge my PR.Thanks

**Comment by ruchikamuddinagiri** [comment]
> @naman360 @PragatiVerma18 Looking forward to make any changes if wanted or needed and if not requesting you to merge my PR.Thanks

Hi,
Currently, the effect can be seen in the title when the user hovers on the title text itself, but not on the card. It would be great if you could implement the same thing, but when the user hovers on the card, instead of the text. Please let me know in case there are any issues in implementing this.

**Comment by AkshaySharma008** [comment]
Congratulation @Muskan-creator.

All the best, Keep Contributing.

**Comment by Muskan-creator** [comment]
Thanks for merging my first PR @AkshaySharma008

**Pull request merged**
