### PR TITLE
Added Contact Us in Light Dark UI, Added Social Media Icons In Footer, Fixed the particle.js issue with body tag and Added 11 events in events.json

### PR DESCRIPTION
**Pull request by K-jais**
1)Added the contact us section in the website in both light and dark UI.
2)Added Social media icons in the footer of the website and added the appropriate style to it in both light and dark UI.
3)Fixed the particle.js issue with the body tag in which the background-color property of the body tag is interfering with particle.js animations by which the dark mode was not working well.
4)Added 11 events in events.json,
1)Digital Ocean Hacktoberfest
2)Google Season of Docs (GSoD)
3)Season of KDE
4)Open Mainframe Project Mentorship Program
5)Linux Kernel Mentorship Program
6)Redox OS Summer of Code
7)Mozilla Winter of Security
8)Hyperledger Mentorship Program
9)Open Summer of Code
10)Alibaba Summer of Code
11)ERPNext Summer of Code

 In light mode,
Screenshot (2169)

====

Screenshot (2170)

====

Screenshot (2172)

In Dark mode,

Screenshot (2173)

====

Screenshot (2174)

====

Screenshot (2175)

Search tag is also working fine in the light as well as dark mode,

Screenshot (2176)

====

Screenshot (2177)

### CODE REVIEW

**Comment by K-jais** [comment]
@ruchikamuddinagiri @PragatiVerma18 @naman360 @servermonk Please review this PR before merging any other PRs.

**Comment by K-jais** [comment]
Please look into this PR.

**Comment by K-jais** [comment]
Please @ruchikamuddinagiri , @PragatiVerma18 review this PR.

**Comment by K-jais** [comment]
Hello sir/ma'am?

**Comment by K-jais** [comment]
Please ma'am/sir look into this PR and review it.

**Comment by K-jais** [comment]
I have fixed the dark mode issue as well as I have added 11 events in events.json along with adding the contact us and the social media icons. In the contact us also, I added the functionality which just sends the mail when a person submits the form.

**Comment by K-jais** [comment]
Ma'am/sir please reply?

**Comment by ruchikamuddinagiri** [comment]
Please squash your commits, resolve merge conflicts and mention the issue number that you've worked on. The PR description must include a precise and short note of what you've done.

**Comment by ruchikamuddinagiri** [comment]
@K-jais why was the issue closed?

**Comment by K-jais** [comment]
> @K-jais why was the PR closed?

Ma'am, I have closed that PR because it was raising too many conflicts.
So I have made a new PR,
PR #226 
Please ma'am look into this PR.

**Pull request closed without merging**
