### PR TITLE
Create new UI For Website 

### PR DESCRIPTION
**Pull request by Dheeraj-01**
# Description

Added some CSS for the button to interactive UI
Make Navigation bar Sticky for good user Experience 
Adding Box Shadow to look good 
Added background-color for footer and a little bit navigation bar  

Fixes # [27](https://github.com/DSC-JSS-NOIDA/foss-events/issues/27)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

#[Hacktoberfest](https://hacktoberfest.digitalocean.com/)

## Screenshot
Screenshot (22115)

------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------

Screenshot (22116)

### CODE REVIEW

**Comment by naman360** [comment]
We appreciate your effort, let other contributors work on this and we will finalize the best UI.

**Comment by Dheeraj-01** [comment]
Yes, And I also work on that? 
If the logo is ready, so it's easy for me to design

**Comment by naman360** [comment]
Please pull latest changes from upstream.

**Comment by Dheeraj-01** [comment]
Yes, I pull my latest changes within an hour

**Comment by Dheeraj-01** [comment]
I think it's good 
Screenshot (22123)

**Comment by naman360** [comment]
Not up to date with `master` branch.

**Comment by Dheeraj-01** [comment]
I have no idea about this, please help me what I do 🤔

**Comment by Dheeraj-01** [comment]
up to date with the master branch.

**Pull request closed without merging**
