### PR TITLE
added events in events.json issue #86 by shraddha jain

### PR DESCRIPTION
**Pull request by Shraddha13Jain**
Successfully added events in events.json which was assigned to me as a participant of GSSoC'21.

### CODE REVIEW

**Comment by AkshaySharma008** [comment]
@Shraddha13Jain what changes have you made in Package-lock.json? As this file is not relevant to the PR you are raising. Please check and commit again

**Comment by Shraddha13Jain** [comment]
> @Shraddha13Jain what changes have you made in Package-lock.json? As this file is not relevant to the PR you are raising. Please check and commit again

@AkshaySharma008  actually to run the server at my end , I need to do 'npm start' and due this command ,package-lock.json file got changed.

**Comment by AkshaySharma008** [comment]
> > @Shraddha13Jain what changes have you made in Package-lock.json? As this file is not relevant to the PR you are raising. Please check and commit again
> 
> @AkshaySharma008 actually to run the server at my end , I need to do 'npm start' and due this command ,package-lock.json file got changed.

If you haven't included any package, then it should not happen, please check again.

**Comment by Shraddha13Jain** [comment]
> > > @Shraddha13Jain what changes have you made in Package-lock.json? As this file is not relevant to the PR you are raising. Please check and commit again
> > 
> > 
> > @AkshaySharma008 actually to run the server at my end , I need to do 'npm start' and due this command ,package-lock.json file got changed.
> 
> If you haven't included any package, then it should not happen, please check again.

@AkshaySharma008 while running this command , the file gets changed. should I make a new pull request without running the server with the same events??

**Pull request closed without merging**
