### PR TITLE
Fixed Issue Number #234 (Adding functional links in contact us section )

### PR DESCRIPTION
**Pull request by abhijeet141**
# Description
Used <a> tag to make links clickable.

Fixes # (issue)
Issue Number #234 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by AkshaySharma008** [comment]
Can you send the screenshot/video of what you have built, along with your changes?

**Comment by abhijeet141** [comment]
Yes sure


https://user-images.githubusercontent.com/67696867/112729015-08a32f80-8f50-11eb-956a-cdcdf4c50c89.mp4

**Comment by AkshaySharma008** [comment]
Congratulation 🥇

**Comment by abhijeet141** [comment]
> Congratulation 🥇

Thank You !! 😊

**Pull request merged**
