### PR TITLE
hover effect on event card

### PR DESCRIPTION
**Pull request by kumarishalini6**
#391 
I have give some hover effect on the event card.

### CODE REVIEW

**Comment by AkshaySharma008** [comment]
Attach screen shot or video or your changes

**Comment by kumarishalini6** [comment]
https://user-images.githubusercontent.com/69043944/120056376-26d8ea80-bfe8-11eb-89f6-15571061bef7.mp4

**Comment by kumarishalini6** [comment]
@AkshaySharma008 done

**Comment by AkshaySharma008** [comment]
Show me the video in Mobile mode too .

**Comment by kumarishalini6** [comment]
Uploading Foss Events - Personal - Microsoft​ Edge 2021-05-29 13-11-53.mp4…

**Comment by kumarishalini6** [comment]
https://user-images.githubusercontent.com/69043944/120062421-bb564380-c00e-11eb-91e0-86e54b9aa284.mp4

**Comment by kumarishalini6** [comment]
@AkshaySharma008 now please check it.

**Pull request merged**
