### PR TITLE
Scroll to top button added

### PR DESCRIPTION
**Pull request by DEEPALI-SUK**
# Description

I have added the Scroll to top button 

Fixes Scroll to Top button on the home page #190

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshot
img1

### CODE REVIEW

**Review by rudrakshi99 — APPROVED** [review]

**Comment by rudrakshi99** [comment]
Looks good to me :+1:

**Comment by DEEPALI-SUK** [comment]
@rudrakshi99 Kindly add labels for GSSOC21 and level for my PR.

**Comment by DEEPALI-SUK** [comment]
@rudrakshi99 Kindly add labels of **GSSOC21** and **level** for my PR.

**Comment by rudrakshi99** [comment]
> @rudrakshi99 Kindly add labels of **GSSOC21** and **level** for my PR.

The issue is already labeled so there is no need to label the PR.

**Comment by DEEPALI-SUK** [comment]
Please could you add labels here also as my scores have not been increased. Kindly, consider my request.

**Comment by rudrakshi99** [comment]
Ok, I have labeled the PR also. Now check, does it increase?

**Comment by DEEPALI-SUK** [comment]
Yes, now it has been increased.
Thank you

**Pull request merged**
