### PR TITLE
Enhanced the search bar

### PR DESCRIPTION
**Pull request by divyanshkhatana**
# Description

I have added CSS property to the search bar 
which includes:
hover
shadow 
change in name
background
image

### CODE REVIEW

**Comment by AkshaySharma008** [comment]
This is not looking so good, please think of something nice. else the basic one is fine for now.

**Comment by divyanshkhatana** [comment]
@AkshaySharma008 i will try more to impove

**Comment by divyanshkhatana** [comment]
@AkshaySharma008  please review it again

**Comment by AkshaySharma008** [comment]
@divyanshkhatana It has few conflicts, try to resolve them and add your new UI screenshot, please.

**Comment by divyanshkhatana** [comment]
@AkshaySharma008  i have resolved the conflicts 

and here is the screenshoot
image

**Comment by AkshaySharma008** [comment]
This is not working fine in Mobile, have a look
image

**Comment by AkshaySharma008** [comment]
Try solving this and create a new PR after creating a new Issue. @divyanshkhatana

**Comment by divyanshkhatana** [comment]
> Try solving this and create a new PR after creating a new Issue. @divyanshkhatana

ok i will work on that

**Pull request merged**
