### PR TITLE
Similarity score instead of exact spelling

### LINKED ISSUE #195: Searching by name must have the exact spelling
Hey, I am a GSSoC 2021 participant and I would like to fix the bug described below so can anyone assign it to me?

**Describe the bug**
When you search for an event by name it must contain the same spelling or at least the same substring for example if we have an event that contains the word javascript and in the search bar we typed java script instead we won't be able to see the event at all.

**To Reproduce**
1. Go to the search bar
2. type the name of any existing event but with a simple difference in spelling
3. See that the event won't appear at all.

**Expected behavior**
Events with all similar names should appear
**Screenshots**
Screenshot (750)
Screenshot (751)

### PR DESCRIPTION
**Pull request by osamamagdy**
# Description
To make the search bar more effective, I implemented a similarity score function depending on the edit distance algorithm.
Then I check if the input is not part of the string, it will appear if it has a similarity score higher than 0.08 (this can be changed later but I but it depending on results by testing)
 
Fixes #195 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ruchikamuddinagiri** [comment]
Hi, i was testing it out but it didn't seem to give me the results I was expecting. Please refer the below screenshot:
image

Maybe there are some tweaks required in the similarity score threshold?

**Comment by osamamagdy** [comment]
@ruchikamuddinagiri I wasn't updating the dom and the JSON file by the calculated score. So, "Mozilla" was there but at the bottom of the page. Thank you for pointing out that it's now updated.

**Comment by osamamagdy** [comment]
@ruchikamuddinagiri I think I can fix the merge conflict if you gave me write access.

**Comment by AkshaySharma008** [comment]
Your branch is having conflicts, please pull and raise a PR again.

**Comment by osamamagdy** [comment]
@ruchikamuddinagiri @AkshaySharma008 @naman360 @PragatiVerma18  I raised another pull request to fix this issue in #266

**Pull request closed without merging**
