### PR TITLE
Fixed issue #170, Created a filter that could filter events between specified dates .

### LINKED ISSUE #170: Introduce a filter that could filter events between specified dates
**Introduction**
Hii, I am a Gssoc participant and I would like to work diligently upon the issue explained below, please assign that to me.
**Description of the problem**
What if a student wants to search for open source events in a particular time frame, maybe he/she is free only for that particular time frame.

**Solution**
I can create a filter in which the user can specify the start date and end date in which the user is vacant and based on that we can get the organizations that host events in that particular interval.

**Approach**
I have access to the start and end date of an event, so I can make use of that and compare the user entered dates with the dates for all the organizations to get the desired results. For comparison of dates, I would use the ISO format.

**Additional context**
I will create an additional field below the search bar in which the user can enter the required dates.

### PR DESCRIPTION
**Pull request by tend2infinity**
# Description

In this filter, we can introduce a left bound and a right bound and then we can selectively get all those events whose tenure lies between the specified range of dates!

Fixes #170 (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshot
FossEvents1
FossEvents2
FossEvents3

### CODE REVIEW

**Comment by ruchikamuddinagiri** [comment]
Will your PR need a specific date format while adding events to events.json?

**Comment by tend2infinity** [comment]
@ruchikamuddinagiri It should be in dd/mm/yyyy format and I feel that this is the standard format which everyone should use. There were some dates in events.json which were in dd/mm/yy format and that is the reason why I did some changes in events.json. I guess we can update the readme to let people know the required format .

**Comment by ruchikamuddinagiri** [comment]
> @ruchikamuddinagiri It should be in dd/mm/yyyy format and I feel that this is the standard format which everyone should use. There were some dates in events.json which were in dd/mm/yy format and that is the reason why I did some changes in events.json. I guess we can update the readme to let people know the required format .

Yes, that will be all. Please raise an issue to specify the date format for events in the Readme. Also, please resolve the merge conflicts.

**Comment by tend2infinity** [comment]
I'll do that for sure

**Comment by tend2infinity** [comment]
I have resolved the conflicts @ruchikamuddinagiri

**Comment by ruchikamuddinagiri** [comment]
Hi, please check for bugs in the code. Let me know if it is working properly on your machine. There were some issues due to which I had to revert the merge.

**Comment by ruchikamuddinagiri** [comment]
Please create a new PR with the changes.

**Comment by tend2infinity** [comment]
Wierd, It was working absolutely perfect for me, nevermind I'll create another PR

**Pull request merged**
